"""Pure logic: filename sanitisation, path construction, CLI argv building."""
def sanitise_name(name: str) -> str: ...
def build_output_paths(song_name: str, base_dirs: dict) -> dict: ...
def build_demucs_argv(input_path: str, separated_dir: str, model: str) -> list[str]: ...